[package]
name = "riscv-emulator"
version = "0.1.0"
authors = ["Joe Thornber <ejt@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
clap = '2.33'
elf = '0.0.10'
fixedbitset = "0.3.1"
intrusive-collections = "0.9"
thiserror = "1.0"

